language: python
sudo: false
addons:
  apt:
    sources:
      - git-core
    packages:
      - git
script:
  - make linkcheck
after_success:
  - openssl aes-256-cbc -K $encrypted_a37343aeb4e3_key -iv $encrypted_a37343aeb4e3_iv -in .travis/github_deploy_key.enc -out "${TRAVIS_BUILD_DIR}/github_deploy_key" -d
  - chmod 600 "${TRAVIS_BUILD_DIR}/github_deploy_key"
  - export GIT_SSH_COMMAND="ssh -i ${TRAVIS_BUILD_DIR}/github_deploy_key"
  - git config user.name travisbuild
  - git config user.email travisbuild@travis-ci
  - git config url."git@github.com:".pushInsteadOf "https://github.com/"
  - git config --add remote.origin.fetch "+refs/heads/gh-pages:refs/remotes/origin/gh-pages"
  - git fetch origin refs/heads/gh-pages
  - git worktree add _build/html -b gh-pages origin/gh-pages
  - make html
  - cd _build/html
  - git add -A
  - git commit -m "Build on commit ${TRAVIS_COMMIT}"
  - git push origin gh-pages
